
###
GET http://localhost:3000/questions

###
POST http://localhost:3000/questions HTTP/1.1
content-type: application/json

{
    "body": "Lorem lorem lorem",
    "answer": "e)"
}

###
GET http://localhost:3000/questions
