version: '3.8'

services:
  postgres:
    image: postgres
    container_name: code-challenge-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-challenge-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
  
  pgadmin:
    image: dpage/pgadmin4 
    restart: always 
    container_name: nest-pgadmin4 
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=123123 
    ports: 
      - '5050:80' 
    depends_on: 
        - postgres
